version: '3'
services:
  app:
    container_name: my-nodejs-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3001:3000'
    depends_on:
      - mongo
    environment:
      - PORT=3000
    volumes:
      - ./src:/usr/src/app/src
    command: ts-node src/index.ts

  mongo:
    container_name: my-mongodb
    image: mongo
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
